title: Plan de sauvegarde et de mise en valeur (PSMV)
description: Ce document produit par le groupe national du CNIG décrit les spécifications des données des plans de sauvegarde et de mise en valeur (PSMV). Ces spécifications visent à standardiser les données géographiques des PSMV.
homepage: https://github.com/cnigfr/schema-plan-sauvegarde
version: 1.3.0
