title: Occupation des sols à grande échelle
description: Prescriptions nationales pour la production d’une base de données d’occupation du sol à grande échelle.
homepage: https://github.com/cnigfr/schema-occupation-sols
version: 1.0.0
