title: Géostandard de réseaux électriques
description: Géostandard vectoriel métier, transverse aux maîtres d’ouvrage de réseaux électriques en espaces extérieurs, basé sur le modèle de StaR-DT et utilisable pour diverses thématiques (transport, distribution, éclairage extérieur, signalisation…).
homepage: https://github.com/cnigfr/schema-reseaux-electriques
version: 1.0.2
