title: Géostandards Risques - Plans de prévention des risques (PPR)
description: La famille des Géostandards Risques a pour objectif de standardiser les données numériques géographiques relatives aux procédures réglementaires de prévention des risques. Ce document est le profil applicatif dédié aux Plans de Prévention des Risques (PPR) Naturels et Technologiques.
homepage: https://github.com/cnigfr/Geostandards-risques-ppr 
version: 1.0.2
lastModified: 2025-11-14