title: Aménagement Numérique des Territoires GraceTHD
description: Le géostandard Aménagement Numérique des Territoires - GraceTHD propose d’apporter un vocabulaire et une structure de données commune aux acteurs impliqués dans le très haut débit et en particulier le déploiement de la fibre optique jusqu'à l'abonné (FttH).
homepage: https://github.com/cnigfr/schema-grace-thd
version: 3.0.0
