title: Schéma de Cohérence Territoriale (SCOT)
description: Ce document produit par le groupe national du CNIG décrit les spécifications des données relatives aux SCOT en standardisant les données géographiques des périmètres de SCOT, et y associant les pièces écrites réglementaires.
homepage: https://github.com/cnigfr/schema-schema-coherence-territoriale
version: 2.0.0
