title: Servitudes d'utilité publique (SUP)
description: Ce présent document décrit les spécifications des données des Servitudes d'Utilité Publique. Ces spécifications visent à standardiser les données géographiques des SUP.
homepage: https://github.com/cnigfr/schema-servitudes-utilite-publique
version: 1.1.1
