title: Socle des Réseaux (STAR-DT)
description: Limité aux objets les plus utiles et en n'abordant aucune logique « métiers », le StaR-DT constitue le socle commun de base décrivant à très grande échelle les réseaux concernés par le Décret DT-DICT afin de permettre à leurs gestionnaires et aux collectivités concernées d’échanger les informations utiles à la géolocalisation des ouvrages en amont des travaux.
homepage: https://github.com/cnigfr/schema-socle-reseaux
version: 1.0.0
