title: Continuités Ecologiques Régionales
description: Prescriptions nationales pour la dématérialisation des Continuités Ecologiques Régionales (CER).
homepage: https://github.com/cnigfr/schema-continuites-ecologiques-regionales
version: 1.0.0
