title: Accessibilité du cheminement en voirie
description: Standard pour les données utiles au cheminement des personnes à mobilité réduite ou en situation de handicap dans les domaines voirie, espace public, et établissements recevant du public.
homepage: https://github.com/cnigfr/schema-accessibilite-voirie
version: 1.2.0
