title: Carte communale
description: Ce document produit par le groupe national du CNIG décrit les spécifications des cartes communales dématérialisées.
homepage: https://github.com/cnigfr/schema-carte-communale
version: 2.0.0
