title: Plan local d'urbanisme
description: Ce document produit par le groupe national du CNIG décrit les spécifications des données des plans locaux d'urbanisme (PLU). Ces spécifications visent à standardiser les données géographiques des PLU.
homepage: https://github.com/cnigfr/schema-plan-local-urbanisme
version: 2.1.0
