title: Dessertes pour le transport de bois
description: Modèle de données partagé afin d’homogénéiser les pratiques lors de la numérisation de données liées au transport du bois.
homepage: https://github.com/cnigfr/schema-desserte-transport-bois
version: 1.0.0
