title: Plan du corps de rue simplifié (PCRS)
description: Le Plan du Corps de Rue Simplifié est un ensemble de données destinées à servir de support cartographique à un grand nombre d'applications requérant une précision d'ordre centimétrique.
homepage: https://github.com/cnigfr/schema-plan-corps-rue-simplifie
version: 2.0.4
