title: Nouveau Schéma de Cohérence Territoriale (SCOT)
description: Ce document produit par le groupe national du CNIG décrit les spécifications des données relatives aux nouveaux SCOT issus de l' ordonnance n°2020-744 du 17 juin 2020 relative à la modernisation des SCOT.
homepage: https://github.com/cnigfr/nouveau-schema-coherence-territoriale
version: 1.0.0
